# This task deletes the extents

- name: Delete extent
  uri:
    url: '{{ url_rest_base_cluster + url_create_extent + item }}'
    url_username: '{{ rest_user }}'
    url_password: '{{ rest_password }}'
    method: DELETE
    force_basic_auth: true
    validate_certs: false
    return_content: true
    body_format: json
    status_code: 204
    timeout: 100
  register: delete_extent_output
  with_items: "{{ extents_list }}"

- name: Delete Extent Response
  debug:
    msg: '{{ delete_extent_output }}'
  when: debug_mode