# This task deletes the provided device

- name: Delete Devices
  uri:
    url: '{{ url_rest_base + item }}'
    url_username: '{{ rest_user }}'
    url_password: '{{ rest_password }}'
    method: DELETE
    force_basic_auth: true
    validate_certs: false
    return_content: true
    body_format: json
    status_code: 204
    timeout: 100
  register: delete_devices_output
  with_items: "{{ devices_list }}"

- name: Delete Devices response
  debug:
    msg: '{{ delete_devices_output }}'
  when: debug_mode
